
workspace:
  path: /drone/src/github.com/FuckAll/Docker-Ci
  base: /drone

build:
    image: golang:1.6.3
    environment:
      - http_proxy=http://172.19.0.2:8118
      - https_proxy=http://172.19.0.2:8118
    commands:
      - /usr/local/go/bin/go get
      - /usr/local/go/bin/go build